name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🛠 Breaking Changes'
    labels:
      - 'breaking-change'
      - 'major'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'security'
version-resolver:
  major:
    labels:
      - 'breaking-change'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
  patch:
    labels:
      - 'patch'
      - 'chore'
      - 'dependencies'
      - 'security'
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '*.yml'
      - '*.yaml'
    branch:
      - '/docs{0,1}\/.+/'
    title:
      - "/chore/i"
      - "/ci/i"
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    files:
      - '*.kt'
    branch:
      - '/feature\/.+/'
template: |
  ## What’s Changed

  $CHANGES
