# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
 - task: SonarCloudPrepare@1
   displayName: 'Prepare analysis configuration'
   inputs:
     SonarCloud: 'SonarClour from Github'
     organization: 'z0r3f'
     scannerMode: 'Other'
     extraProperties: |
       # Additional properties that will be passed to the scanner,
       # Put one key=value per line, example:
       # sonar.exclusions=**/*.bin
       sonar.projectKey=z0r3f_weather-app
       sonar.projectName=Weather Bot
       sonar.coverage.jacoco.xmlReportPaths=$(System.DefaultWorkingDirectory)/**/target/site/jacoco-aggregate/jacoco.xml

 - task: DownloadSecureFile@1
   name: GitCryptSecretKey
   displayName: "Download secret key"
   inputs:
     secureFile: GitCryptSecretKey
 - task: Bash@3
   displayName: "GitCrypt Unlock"
   inputs:
     targetType: "inline"
     script: |
       sudo apt-get update
       sudo apt-get install git-crypt
       git-crypt unlock $(GitCryptSecretKey.secureFilePath)

 - task: Maven@3
   inputs:
     mavenPomFile: 'pom.xml'
     publishJUnitResults: true
     testResultsFiles: '**/surefire-reports/TEST-*.xml'
     javaHomeOption: 'JDKVersion'
     jdkVersionOption: '1.17'
     mavenVersionOption: 'Default'
     mavenOptions: '-Xmx3072m'
     mavenAuthenticateFeed: false
     effectivePomSkip: false
     sonarQubeRunAnalysis: true
     sqMavenPluginVersionChoice: 'pom'

 - script: |
     version=$(cat pom.xml | grep '^.*<version>' | sed -n 2p | awk -F'[><]' '{print $3}')
     echo "##vso[task.setvariable variable=pomVersion;isOutput=true]$version"
   displayName: 'Get version from pom.xml'
   name: tagVersion

 - task: PublishTestResults@2
   displayName: 'Publish Test Results'
   inputs:
     testResultsFormat: 'JUnit'
     testResultsFiles: '**/TEST-*.xml'

 - task: PublishCodeCoverageResults@1
   displayName: 'Publish Code Coverage Results'
   inputs:
     codeCoverageTool: 'JaCoCo'
     summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/target/site/jacoco-aggregate/jacoco.xml'
     reportDirectory: '$(System.DefaultWorkingDirectory)/**/target/site/jacoco-aggregate'
     pathToSources: |
      '$(System.DefaultWorkingDirectory)/architecture/src/main/kotlin'
      '$(System.DefaultWorkingDirectory)/core/src/main/kotlin'
      '$(System.DefaultWorkingDirectory)/bot/src/main/kotlin'

 - task: SonarCloudPublish@1
   displayName: 'Publish results on build summary'
   inputs:
     pollingTimeoutSec: '1000'

 - task: Docker@2
   condition: and(succeeded(), eq(variables.isMaster, true))
   inputs:
     containerRegistry: 'DockerWeather'
     repository: 'z0r3f/weather-docker'
     command: 'buildAndPush'
     Dockerfile: '**/Dockerfile'
     tags: |
       $(tagVersion.pomVersion)
       latest
