# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
 - task: SonarCloudPrepare@1
   displayName: 'Prepare analysis configuration'
   inputs:
     SonarCloud: 'SonarSC'
     organization: 'ferozar'
     scannerMode: 'Other'
     extraProperties: |
       # Additional properties that will be passed to the scanner,
       # Put one key=value per line, example:
       # sonar.exclusions=**/*.bin
       sonar.projectKey=ferozar_Weather-Bot
       sonar.projectName=Weather Bot

 - task: DownloadSecureFile@1
   name: GitCryptSecretKey
   displayName: "Download secret key"
   inputs:
     secureFile: GitCryptSecretKey
 - task: Bash@3
   displayName: "GitCrypt Unlock"
   inputs:
     targetType: "inline"
     script: |
       sudo apt-get update
       sudo apt-get install git-crypt
       git-crypt unlock $(GitCryptSecretKey.secureFilePath)

 - task: DownloadSecureFile@1
   inputs:
    secureFile: 'f5t5p12'
   displayName: 'Download cer'
 - task: CopyFiles@2
   inputs:
    Contents: $(GitCryptSecretKey.f5t5p12)
    TargetFolder: '$(System.DefaultWorkingDirectory)/weather-delivery/src/main/resources/cer/'
   displayName: 'Copy cer'

 - task: Maven@3
   inputs:
     mavenPomFile: 'pom.xml'
     publishJUnitResults: true
     testResultsFiles: '**/surefire-reports/TEST-*.xml'
     javaHomeOption: 'JDKVersion'
     jdkVersionOption: '1.17'
     mavenVersionOption: 'Default'
     mavenOptions: '-Xmx3072m'
     mavenAuthenticateFeed: false
     effectivePomSkip: false
     sonarQubeRunAnalysis: true
     sqMavenPluginVersionChoice: 'pom'

 - task: SonarCloudPublish@1
   displayName: 'Publish results on build summary'
   inputs:
     pollingTimeoutSec: '1000'

 - task: Docker@2
   inputs:
     containerRegistry: 'DockerWeather'
     repository: 'z0r3f/weather-docker'
     command: 'buildAndPush'
     Dockerfile: '**/Dockerfile'
     tags: |
       $(Build.BuildId)
       latest
