weather:
  api-key: "<YOUR-API-KEY>"
  url-base: "https://api.openweathermap.org"
  data:
    url: "${weather.url-base}/data/2.5"
  geo:
    url: "${weather.url-base}/geo/1.0/direct"
    results-limit: 5

telegram:
  token: "<YOUR TELEGRAM TOKEN>"
  webhook: "<YOUR WEBHOOK POST ENDPOINT>"

micronaut:
  ssl:
    enabled: true
    key-store:
      path: "<YOUR DIGITAL CERTIFICATE>"
      password: "<YOUR DIGITAL CERTIFICATE PASSWORD>"
  server:
    netty:
      log-level: DEBUG
  caches:
    search-by-name:
      expire-after-write: P1D
    forecast-by-coordinate:
      expire-after-write: PT3H

flyway:
  datasources:
    default:
      enabled: true

datasources:
  default:
    url: "<YOUR DB URL>"
    username: "<YOUR DB USERNAME >"
    password: "<YOUR DB PASSWORD >"
    driverClassName: org.postgresql.Driver

jpa:
  default:
    entity-scan:
      packages: "me.fernando.chat.db.entities"
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
